/**
 * Predefined Templates for Complex AI Commands
 *
 * These templates define multi-shape layouts that the AI can create
 * with a single command like "create a login form".
 */

const TEMPLATES = {
  loginForm: {
    name: "loginForm",
    description: "Login form with username, password fields, and button",
    shapes: [
      {
        type: "text",
        text: "Username",
        offsetX: 0,
        offsetY: 0,
        fontSize: 14,
        fill: "#2d3748",
        fontFamily: "Arial",
        fontStyle: "normal",
        align: "left",
      },
      {
        type: "rectangle",
        width: 200,
        height: 36,
        offsetX: 0,
        offsetY: 24,
        fill: "#ffffff",
        stroke: "#cbd5e0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Password",
        offsetX: 0,
        offsetY: 76,
        fontSize: 14,
        fill: "#2d3748",
        fontFamily: "Arial",
        fontStyle: "normal",
        align: "left",
      },
      {
        type: "rectangle",
        width: 200,
        height: 36,
        offsetX: 0,
        offsetY: 100,
        fill: "#ffffff",
        stroke: "#cbd5e0",
        strokeWidth: 1,
      },
      {
        type: "rectangle",
        width: 200,
        height: 40,
        offsetX: 0,
        offsetY: 152,
        fill: "#3B82F6",
      },
      {
        type: "text",
        text: "Login",
        offsetX: 80,
        offsetY: 162,
        fontSize: 16,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontStyle: "bold",
        align: "center",
      },
    ],
  },

  trafficLight: {
    name: "trafficLight",
    description: "Traffic light with red, yellow, and green lights",
    shapes: [
      {
        type: "rectangle",
        width: 80,
        height: 220,
        offsetX: 0,
        offsetY: 0,
        fill: "#4B5563",
      },
      {
        type: "circle",
        radius: 28,
        offsetX: 40,
        offsetY: 40,
        fill: "#EF4444",
      },
      {
        type: "circle",
        radius: 28,
        offsetX: 40,
        offsetY: 110,
        fill: "#FBBF24",
      },
      {
        type: "circle",
        radius: 28,
        offsetX: 40,
        offsetY: 180,
        fill: "#10B981",
      },
    ],
  },

  navigationBar: {
    name: "navigationBar",
    description: "Navigation bar with Home, About, Contact links",
    shapes: [
      {
        type: "rectangle",
        width: 800,
        height: 60,
        offsetX: 0,
        offsetY: 0,
        fill: "#1F2937",
      },
      {
        type: "text",
        text: "Home",
        offsetX: 20,
        offsetY: 22,
        fontSize: 16,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontStyle: "normal",
        align: "left",
      },
      {
        type: "text",
        text: "About",
        offsetX: 380,
        offsetY: 22,
        fontSize: 16,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontStyle: "normal",
        align: "left",
      },
      {
        type: "text",
        text: "Contact",
        offsetX: 720,
        offsetY: 22,
        fontSize: 16,
        fill: "#ffffff",
        fontFamily: "Arial",
        fontStyle: "normal",
        align: "left",
      },
    ],
  },

  signupForm: {
    name: "signupForm",
    description: "Signup form with email, password, and confirm password",
    shapes: [
      {
        type: "text",
        text: "Email",
        offsetX: 0,
        offsetY: 0,
        fontSize: 14,
        fill: "#2d3748",
      },
      {
        type: "rectangle",
        width: 250,
        height: 36,
        offsetX: 0,
        offsetY: 24,
        fill: "#ffffff",
        stroke: "#cbd5e0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Password",
        offsetX: 0,
        offsetY: 76,
        fontSize: 14,
        fill: "#2d3748",
      },
      {
        type: "rectangle",
        width: 250,
        height: 36,
        offsetX: 0,
        offsetY: 100,
        fill: "#ffffff",
        stroke: "#cbd5e0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Confirm Password",
        offsetX: 0,
        offsetY: 152,
        fontSize: 14,
        fill: "#2d3748",
      },
      {
        type: "rectangle",
        width: 250,
        height: 36,
        offsetX: 0,
        offsetY: 176,
        fill: "#ffffff",
        stroke: "#cbd5e0",
        strokeWidth: 1,
      },
      {
        type: "rectangle",
        width: 250,
        height: 44,
        offsetX: 0,
        offsetY: 228,
        fill: "#10B981",
      },
      {
        type: "text",
        text: "Sign Up",
        offsetX: 95,
        offsetY: 240,
        fontSize: 16,
        fill: "#ffffff",
        fontStyle: "bold",
      },
    ],
  },

  dashboard: {
    name: "dashboard",
    description: "Dashboard with title and stat cards",
    shapes: [
      {
        type: "text",
        text: "Dashboard",
        offsetX: 0,
        offsetY: 0,
        fontSize: 24,
        fill: "#1a202c",
        fontStyle: "bold",
      },
      {
        type: "rectangle",
        width: 180,
        height: 100,
        offsetX: 0,
        offsetY: 50,
        fill: "#ffffff",
        stroke: "#e2e8f0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Users",
        offsetX: 60,
        offsetY: 70,
        fontSize: 14,
        fill: "#718096",
      },
      {
        type: "text",
        text: "1,234",
        offsetX: 50,
        offsetY: 100,
        fontSize: 28,
        fill: "#2d3748",
        fontStyle: "bold",
      },
      {
        type: "rectangle",
        width: 180,
        height: 100,
        offsetX: 200,
        offsetY: 50,
        fill: "#ffffff",
        stroke: "#e2e8f0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Revenue",
        offsetX: 250,
        offsetY: 70,
        fontSize: 14,
        fill: "#718096",
      },
      {
        type: "text",
        text: "$12.5K",
        offsetX: 235,
        offsetY: 100,
        fontSize: 28,
        fill: "#2d3748",
        fontStyle: "bold",
      },
      {
        type: "rectangle",
        width: 180,
        height: 100,
        offsetX: 400,
        offsetY: 50,
        fill: "#ffffff",
        stroke: "#e2e8f0",
        strokeWidth: 1,
      },
      {
        type: "text",
        text: "Growth",
        offsetX: 455,
        offsetY: 70,
        fontSize: 14,
        fill: "#718096",
      },
      {
        type: "text",
        text: "+23%",
        offsetX: 455,
        offsetY: 100,
        fontSize: 28,
        fill: "#10B981",
        fontStyle: "bold",
      },
    ],
  },
};

module.exports = {TEMPLATES};
